import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Chat from '@/components/Chat_Frame/ChatFrame'
import Message from '@/components/Contact_Frame/ContactFrame'
import Sidebar from '@/components/Sidebar/Sidebar'
import Navbar from '@/components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Navbar/>
      <div className='flex justify-center gap-2 mt-2'>
      <Sidebar/>   
      <Message/>
      <Chat/>
      

         
      </div>
     
     
    </>
  )
}
